
create table
  public.birthdays (
    id bigint generated by default as identity,
    user_id uuid not null,
    name text not null,
    date date not null,
    created_at timestamp with time zone not null default now(),
    constraint birthdays_pkey primary key (id),
    constraint birthdays_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade
  ) tablespace pg_default;
