import { Platform } from 'react-native';

export const Colors = {
  light: {
    text: '#11181C',
    textSecondary: '#687076',
    background: '#FFFFFF',
    surface: '#e7e7e7ff',
    tint: '#464646ff',
    accent: '#0A7EA4',
    icon: '#687076',
    tabIconDefault: '#687076',
    tabIconSelected: '#0A7EA4',
    primary: '#0A7EA4',
    card: '#FFFFFF',
    border: '#E5E7#FF5252',
    warning: '#FF9800',
    success: '#4CAF50',
  },
  dark: {
    text: '#ECEDEE',
    textSecondary: '#9BA1A6',
    background: '#151718',
    surface: '#1F1F1F',
    tint: '#FFFFFF',
    accent: '#47A3F3',
    icon: '#9BA1A6',
    tabIconDefault: '#9BA1A6',
    tabIconSelected: '#FFFFFF',
    primary: '#47A3F3',
    card: '#1F1F1F',
    border: '#2A2A2A',
    error: '#FF5252',
    warning: '#FF9800',
    success: '#4CAF50',
  },
  forest: {
    text: '#E0E0E0',
    textSecondary: '#BDBDBD',
    background: '#1B2D2A',
    surface: '#2C3E3A',
    tint: '#A5D6A7',
    accent: '#81C784',
    icon: '#BDBDBD',
    tabIconDefault: '#BDBDBD',
    tabIconSelected: '#A5D6A7',
    primary: '#81C784',
    card: '#2C3E3A',
    border: '#4F5B5A',
    error: '#EF9A9A',
    warning: '#FFCC80',
    success: '#A5D6A7',
  },
  ocean: {
    text: '#E0F7FA',
    textSecondary: '#B2EBF2',
    background: '#003366',
    surface: '#004C99',
    tint: '#80DEEA',
    accent: '#4DD0E1',
    icon: '#B2EBF2',
    tabIconDefault: '#B2EBF2',
    tabIconSelected: '#80DEEA',
    primary: '#4DD0E1',
    card: '#004C99',
    border: '#0066CC',
    error: '#FF8A80',
    warning: '#FFD180',
    success: '#B9F6CA',
  },
  sunset: {
    text: '#212121',
    textSecondary: '#757575',
    background: '#FFDDC1',
    surface: '#FFC299',
    tint: '#FF8A65',
    accent: '#FF7043',
    icon: '#757575',
    tabIconDefault: '#757575',
    tabIconSelected: '#FF8A65',
    primary: '#FF7043',
    card: '#FFC299',
    border: '#FFAB91',
    error: '#FF5252',
    warning: '#FF9800',
    success: '#4CAF50',
  },
};

export const Fonts = Platform.select({
  ios: {
    /** iOS `UIFontDescriptorSystemDesignDefault` */
    sans: 'system-ui',
    /** iOS `UIFontDescriptorSystemDesignSerif` */
    serif: 'ui-serif',
    /** iOS `UIFontDescriptorSystemDesignRounded` */
    rounded: 'ui-rounded',
    /** iOS `UIFontDescriptorSystemDesignMonospaced` */
    mono: 'ui-monospace',
  },
  default: {
    sans: 'normal',
    serif: 'serif',
    rounded: 'normal',
    mono: 'monospace',
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});
